[workspace]

members = [
    "codegen",
    "common",
    "compiler",
    "data_structures",
    "diagnostics",
    "fixtures",
    "fuzzer",
    "hir",
    "lexer",
    "log",
    "lowering",
    "lsp",
    "parser",
    "source",
    "ty",
    "typecheck",
    "tests"
]