#[derive(Debug, PartialEq)]
pub enum Token {
    Assign,
    Colon,
    Comma,
    Dot,
    EOF,
    Exclaim,
    ForwardSlash,
    Ident(String),
    Keyword(String),
    LCaret,
    LCurlyBracket,
    LParen,
    RCaret,
    RCurlyBracket,
    RParen,
    SemiColon,
    String(String),
    Number(i64),
}
